import dns from "node:dns";
dns.setServers(["8.8.8.8", "8.8.4.4"]);

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className='h-full antialiased'
    >
      <body className="min-h-full flex flex-col ">
        <Navbar />
        <main className="mx-4 md:mx-20 lg:mx-30">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
